version: '3'

volumes: 
    prometheus_data: {}
    grafana_data: {}

services: 

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes: 
          - ./config/prometheus:/etc/prometheus
          - prometheus_data:/prometheus
        command: 
           - '--config.file=/etc/prometheus/prometheus.yml'     
           - '--storage.tsdb.path=/prometheus'
           - '--web.console.libraries=/usr/share/prometheus/console_libraries'   
           - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
          - 9090:9090
    node_exporter:
        image: prom/node-exporter
        container_name: node_exporter
        restart: unless-stopped
        ports: 
          - 9100:9100
    cadvisor:
        image: google/cadvisor
        container_name: caAdvisor
        restart: unless-stopped
        volumes: 
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
          - 8080:8080
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        ports: 
             - 3000:3000
        volumes:    
           - grafana_data:/var/lib/grafana
    proget-postgres:
        image: postgres:9.5
        container_name: proget-postgres
        restart: unless-stopped
        volumes:
          - /var/proget/db:/var/lib/postgresql/data
    proget:
        image: inedo/proget
        container_name: proget
        volumes:
          - /var/proget/packages:/var/proget/packages
          - /var/proget/extensions:/var/proget/extensions
        restart: unless-stopped
        ports: 
          - 80:80
        depends_on:
          - proget-postgres
    teamcity-server:
        image:  jetbrains/teamcity-server
        container_name: teamcity-server
        volumes: 
          - /var/teamcity_server/data:/data/teamcity_server/datadir
          - /var/teamcity_server/logs:/data/teamcity_server/logs
        restart: unless-stopped
        ports: 
          - 81:8111

