version: '3'

volumes: 
    prometheus_data: {}
    grafana_data: {}
    rabbitmq01_data: {}
    elasticsearch_data: {}
    mssqlserver_data: {}
services: 

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes: 
          - ./config/prometheus:/etc/prometheus
          - prometheus_data:/prometheus
        command: 
           - '--config.file=/etc/prometheus/prometheus.yml'     
           - '--storage.tsdb.path=/prometheus'
           - '--web.console.libraries=/usr/share/prometheus/console_libraries'   
           - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
          - 9090:9090
    node_exporter:
        image: prom/node-exporter
        container_name: node_exporter
        restart: unless-stopped
        ports: 
          - 9100:9100
    cadvisor:
        image: google/cadvisor
        container_name: caAdvisor
        restart: unless-stopped
        volumes: 
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        ports:
          - 8080:8080
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        ports: 
             - 3000:3000
        volumes:    
           - grafana_data:/var/lib/grafana
    proget-postgres:
        image: postgres:9.5
        container_name: proget-postgres
        restart: unless-stopped
        volumes:
          - /var/proget/db:/var/lib/postgresql/data
    proget:
        image: inedo/proget
        container_name: proget
        volumes:
          - /var/proget/packages:/var/proget/packages
          - /var/proget/extensions:/var/proget/extensions
        restart: unless-stopped
        ports: 
          - 80:80
        depends_on:
          - proget-postgres
    teamcity-server:
        image:  jetbrains/teamcity-server
        container_name: teamcity-server
        volumes: 
          - /var/teamcity_server/data:/data/teamcity_server/datadir
          - /var/teamcity_server/logs:/data/teamcity_server/logs
        restart: unless-stopped
        ports: 
          - 81:8111
    teamcity-agent-01:
        image: gjaminon/teamcity-agent-aspnetcore
        container_name: teamcity-agent-01
        environment: 
           - SERVER_URL=teamcity-server:8111
        volumes: 
           - /var/data/teamcity_agent_01/config:/data/teamcity_agent/conf
    rabbitmq-01:
        image: gjaminon/rabbitmq
        container_name: rabbitmq-01
        restart: unless-stopped
        hostname: rabbitmq1
        ports:
          - "15672:15672"
          - "5672:5672"
        volumes:
          - rabbitmq01_data:/var/lib/rabbitmq/mnesia
    elasticsearch: 
        image: gjaminon/elasticsearch-kibana-dev
        container_name: elasticsearch
        restart: unless-stopped
        ports: 
          - "9200:9200"
          - "5601:5601"
        volumes: 
          -  elasticsearch_data:/usr/share/elasticsearch/data
    elasticsearch-exporter:
        image: gjaminon/elasticsearch_exporter
        container_name: elasticsearch-exporter
        command: 
           - '-es.uri=http://elasticsearch:9200'
        restart: unless-stopped
        ports: 
           - 9108:9108
    mssqlserver:
        image:  microsoft/mssql-server-linux:2017-latest
        container_name: mssqlserver
        restart: unless-stopped
        environment: 
          ACCEPT_EULA: Y
          SA_PASSWORD: "DevOpsSql123"          
        ports: 
          - 1433:1433
        volumes: 
          - mssqlserver_data:/var/opt/mssql
















